apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: permtest1
  janus-idp.io/tekton: permtest1
  backstage.io/kubernetes-id: permtest1
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: permtest1
resources: 
- initialize-namespace.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
