---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: permtest1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: permtest1 
  name: permtest1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi