apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: permtest1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: permtest1 
  name: permtest1
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: permtest1 
