apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: permtest1 
  janus-idp.io/tekton: permtest1
  backstage.io/kubernetes-id: permtest1
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: permtest1
resources: 
- application-dev.yaml